name: Ruby Gem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        gem install bundler
        bundle install
        bundle exec jekyll build
        cp CNAME _site/CNAME
        
    - name: Commit files
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        ls -Q | grep -v _site | xargs rm -rf
        mv _site/* .
        rm -rf _site
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
